framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                #serializer: App\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: app
                        type: headers
                        default_publish_routing_key: high
                    queues:
                        messages_high:
                            binding_keys: [ high ]
                            binding_arguments:
                                x-match: all
                                source: toto
                        messages_normal:
                            binding_keys: [ normal ]

        routing:
            # Route your messages to the transports
            App\Message\NotificationMessage: async
