[rabbit]
host = "rabbit"
port = 5672
username = "rabbitmq"
password = "rabbitmq"
vhost = "/"
queue_prefix = ""
reconnections = 0

[[rabbit.queues]]
id = 1
queue_name = "messages"
consumer_name = "rust-consumer"
command = "php /var/www/html/bin/console app:index"
command_timeout = 30
base64 = false
start_hour = "00:00:00"
end_hour = "23:59:59"
count = 1
retry_wait = 120
retry_mode = "incremental"
enabled = true

[database]
enabled = false
host = ""
port = 3306
user = ""
password = ""
db_name = ""
retries = 3